# Security Configuration Assessment
# Audit for PureHVNC malware
# Copyright (C) 2024, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
policy:
  id: "PureHVNC_malware"
  file: "purehvnc_malware_check.yml"
  name: "PureHVNC malware Windows OS check"
  description: "Detecting PureHVNC malware"

requirements:
  title: "Checking PureHVNC malware on Windows based systems"
  description: "Requirements for running the audit policy under a Windows platform"
  condition: all
  rules:
    - 'r:HKEY_LOCAL_MACHINE\SAM\SAM'

checks:
  - id: 77000
    title: "Checking for Possible PureHVNC malware artifacts (ZIP files) in Downloads folder"
    description: "Check for ZIP files associated with PureHVNC malware in Downloads folder."
    remediation: "Delete the files DXJS.zip and FTSP.zip from the Downloads folder."
    condition: all
    rules:
      - 'not f:C:\Users\*\Downloads\DXJS.zip'
      - 'not f:C:\Users\*\Downloads\FTSP.zip'

  - id: 77001
    title: "Checking for Possible PureHVNC malware artifacts (Python scripts) in Downloads folder"
    description: "Check for Python scripts associated with PureHVNC malware in Downloads folder."
    remediation: "Delete the Python scripts and the Python folder from the Downloads folder."
    condition: all
    rules:
      - 'not f:C:\Users\*\Downloads\Python\Python312\money.py'
      - 'not f:C:\Users\*\Downloads\Python\Python312\update.py'
      - 'not f:C:\Users\*\Downloads\Python\Python312\upload.py'
      - 'not f:C:\Users\*\Downloads\Python\Python312\time.py'
      - 'not f:C:\Users\*\Downloads\Python\Python312\kam.py'
      - 'not f:C:\Users\*\Downloads\Python\Python312\moment.py'
      - 'not f:C:\Users\*\Downloads\Python\Python312\info.py'

  - id: 77002
    title: "Checking for Possible PureHVNC malware artifacts (batch file) in Downloads folder"
    description: "Check for batch file associated with PureHVNC malware in Downloads folder."
    remediation: "Delete the startuppp.bat file from the Downloads folder."
    condition: all
    rules:
      - 'not f:C:\Users\*\Downloads\startuppp.bat'

  - id: 77003
    title: "Checking for Possible PureHVNC malware artifacts (folders) in Downloads folder"
    description: "Check for folders associated with PureHVNC malware in Downloads folder."
    remediation: "Delete the Python and Print folders from the Downloads folder."
    condition: all
    rules:
      - 'not d:C:\Users\*\Downloads\Python'
      - 'not d:C:\Users\*\Downloads\Print'