# Security Configuration Assessment
# Audit for Maranhao Stealer malware
# Copyright (C) 2025, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
policy:
  id: "maranhao_stealer_malware"
  file: "maranhao_stealer_check.yml"
  name: "Maranhao Stealer malware Windows OS check"
  description: "Detecting Maranhao Stealer malware artifacts and persistence mechanisms"

requirements:
  title: "Checking for Maranhao Stealer malware on Windows based systems"
  description: "Requirements for running the audit policy under a Windows platform"
  condition: all
  rules:
    - 'r:HKEY_LOCAL_MACHINE\SAM\SAM'

checks:
  - id: 78000
    title: "Maranhao stealer artifact: Checking for Maranhao Stealer installation directory"
    description: "Check for the presence of the malicious installation directory"
    remediation: "Investigate and remove the Microsoft Updater directory. Investigate and delete HKCU/Software/Microsoft/Windows/CurrentVersion/Run/updater from the Windows Registry"
    condition: all
    rules:
      - 'not d:C:\Users\*\AppData\Local\Programs\Microsoft Updater'

  - id: 78001
    title: "Maranhao Stealer artifact: Checking for main executable (updater.exe)"
    description: "Check for the presence of the main Maranhao executable in the AppData directory"
    remediation: "Investigate and remove the updater executable"
    condition: all
    rules:
      - 'not f:C:\Users\*\AppData\Local\Programs\Microsoft Updater\updater.exe'

  - id: 78002
    title: "Maranhao Stealer artifact: Checking for hidden cryptographic key file (crypto.key)"
    description: "Check for the presence of the hidden crypto key file."
    remediation: "Investigate and remove the crypto key file"
    condition: all
    rules:
      - 'not f:C:\Users\*\AppData\Local\Programs\Microsoft Updater\crypto.key'