# Security Configuration Assessment
# Audit for Snake keyloger malware
# Copyright (C) 2024, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
policy:
  id: "trojan_snake"
  file: "trojan_snake.yml"
  name: "Snake trojan - Windows"
  description: "Detecting Snake keylogger"

requirements:
  title: "Checking for Snake keylogger artifacts on Windows based systems"
  description: "Requirements for running the audit policy under a Windows platform"
  condition: all
  rules:
    - 'r:HKEY_LOCAL_MACHINE\SAM\SAM'

checks:
  - id: 71000
    title: "Checking for possible Snake keylogger malware artifacts in Roaming folder"
    description: "Check for Snake keylogger artifacts in Roaming folder"
    remediation: "Delete the WeENKtk.exe file from the Roaming folder"
    condition: all
    rules:
      - 'not f:C:\Users\*\AppData\Roaming\WeENKtk.exe'    

  - id: 71001
    title: "Check if Snake keylogger artifact (WeENKtk.exe) is present in Windows Defender exclusion list"
    description: "Check for Snake keylogger artifact is in Windows Defender exclusion list"
    remediation: "Delete the entry from the Windows Defender exclcusion list"
    condition: all
    rules:
      - 'not r:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths -> C:\Users\*\AppData\Roaming\WeENKtk.exe'

  - id: 71002
    title: "Check if scheduled task (WeENKtk) exists in the Updates registry path"
    description: "Check if the specified task is created in the Task Scheduler under the Updates registry path"
    remediation: "Delete the WeENKtk registry folder"
    condition: all
    rules:
      - 'not r:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\Updates\WeENKtk'