# Security Configuration Assessment
# Auto-color Malware Detection for Linux Systems
# Copyright (C) 2025, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation

policy:
  id: "autocolor_check"
  file: "autocolor_check.yml"
  name: "Auto-color malware check"
  description: "Checking Auto-color malware infection for Unix/Linux-based systems."


requirements:
  title: "Checking Auto-color on Unix/Linux based systems."
  description: "Check that the system is Unix/Linux based."
  condition: any
  rules:
    - 'f:/etc/passwd'


checks:
  - id: 10001
    title: "Check for Auto-color malware duplication in the /var/log/cross directory."
    description: "Detects the presence of /var/log/cross/auto-color, a duplicate created by Auto-color malware."
    rationale: "Auto-color duplicates itself to /var/log/cross/auto-color to masquerade as a legitimate file."
    remediation: "Investigate /var/log/cross/auto-color. If confirmed malicious, delete with: sudo rm /var/log/cross/auto-color. Verify no legitimate use."
    compliance:
      - mitre_attack: ["T1036.005 - Masquerading: Match Legitimate Name or Location"]
      - mitre_attack: ["T1059 - Command and Scripting Interpreter"]
    condition: all
    rules:
     - 'not f:/var/log/cross/auto-color'




  - id: 100002
    title: "Auto-color C2 Configuration Files"
    description: "Detects config-err-* files in /var/log/cross/, /tmp/, or /tmp/cross/0/,created by Auto-color for C2 communication."
    rationale: "Auto-color creates files like config-err-XXXXXXXX for encrypted C2 communication."
    remediation: "Investigate $cross_dir for config-err-* files. If malicious, delete with: sudo rm -f $cross_dir/config-err-*. Delete directories if empty."
    compliance:
      - mitre_attack: ["T1071.001 - Application Layer Protocol: Web Protocols"]
      - mitre_attack: ["T1008 - Fallback Channels"]
      - mitre_attack: ["T1568 - Dynamic Resolution"]
    condition: none
    rules:
      - 'c:find /var/log/cross -type f -name "config-err-*"'
      - 'c:find /tmp -type f -name "config-err-*"'
      - 'c:find /tmp/cross/0 -type f -name "config-err-*"'
      - 'c:find /var/log/cross/0 -type f -name "config-err-*"'




  - id: 100003
    title: "Auto-color Network Activity Hiding Files in /tmp/cross"
    description: "Detects the presence of the /tmp/cross directory and any files within it, used by Auto-color to hide C2 network activity by filtering /proc/net/tcp data."
    rationale: "Auto-color hooks file access functions (open, openat64, fopen, fopen64) to block reading of /proc/net/tcp, which lists TCP connections. It filters C2-related IPs and ports, saving cleaned-up data in temporary files under /tmp/cross to evade detection by tools like netstat."
    remediation: "Investigate /tmp/cross for suspicious files. If malicious, delete with: sudo rm -f /tmp/cross/*; sudo rmdir /tmp/cross. Verify no legitimate use before deletion."
    compliance:
      - mitre_attack: ["T1071.001 - Application Layer Protocol: Web Protocols"]
      - mitre_attack: ["T1008 - Fallback Channels"]
      - mitre_attack: ["T1568 - Dynamic Resolution"]
      - mitre_attack: ["T1562.001 - Impair Defenses: Disable or Modify Tools"]
    condition: none
    rules:
      - 'f:/tmp/cross/0/tcp'
      - 'c:find /tmp/cross -type f -name "*"'